name: MyWorkFlow file

on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: Ubuntu-20.04

    steps:
    - name: greeting steps
    
      run:
        echo "Hello hansum"

    - name: Checkout my codes
      uses: actions/checkout@v4
    - name: print content
      run:
        ls
